[config]
schemaVersion = "0.0.1"

[package]
namespace = "Starfish"
name = "StaticTransportViews"
versionNumber = "0.1.0"
description = "Remove the view resets when closing transport window"
websiteUrl = "https://github.com/wheezydastarfish/staticTransportViews"
containsNsfwContent = false

[package.dependencies]
# BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./ts-build"

[publish]
repository = "https://thunderstore.io"
communities = [ "cities-skylines-ii", ]
categories = [ "mods" ]
